//! End-to-end differential test against the Kotlin reference parser.
//!
//! Fixtures are generated by
//! `mgroup3/test/kotlin/.../ParserFixtureGenTest.kt`. To regenerate:
//!   /Users/joonsoo/Documents/apps/bibix4/bibix4 runMgroup3Test
//!
//! Each fixture under `tests/fixtures/parser/<case>/` has:
//!   - `data.pb`     — raw Mgroup3ParserData bytes
//!   - `grammar.txt` — the grammar source
//!   - `inputs/<idx>_<slug>/{input.txt, golden.txt}` — one input/golden pair
//!
//! `golden.txt` is either `REJECTED\n` or `ACCEPTED\n` followed by `# gen N`
//! blocks of `<symbolId> <pointer> <beginGen> <endGen>` lines sorted by
//! (symbolId, pointer, beginGen, endGen). The Rust side serializes
//! `kernels_history` identically and byte-compares.

use std::collections::BTreeSet;
use std::fs;
use std::path::PathBuf;

use mgroup3_native::parser::{Mgroup3Parser, ParsingError};
use mgroup3_native::parsing_ctx::KtlibKernel;
use mgroup3_native::proto::com::giyeok::jparser::mgroup3::proto::Mgroup3ParserData;
use prost::Message;

fn committed_fixtures_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/parser")
}

fn generated_fixtures_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/parser_generated")
}

fn serialize_kernels_history(history: &[std::collections::HashSet<KtlibKernel>]) -> String {
    let mut out = String::new();
    out.push_str("ACCEPTED\n");
    for (gen_idx, kernels) in history.iter().enumerate() {
        out.push_str(&format!("# gen {}\n", gen_idx));
        let sorted: BTreeSet<KtlibKernel> = kernels.iter().copied().collect();
        for k in sorted {
            out.push_str(&format!(
                "{} {} {} {}\n",
                k.symbol_id, k.pointer, k.begin_gen, k.end_gen
            ));
        }
    }
    out
}

fn run_case(case_dir: &std::path::Path) -> Vec<String> {
    let mut failures = Vec::new();
    let data_path = case_dir.join("data.pb");
    let bytes = match fs::read(&data_path) {
        Ok(b) => b,
        Err(e) => {
            failures.push(format!(
                "{}: cannot read data.pb: {}",
                case_dir.display(),
                e
            ));
            return failures;
        }
    };
    let data = match Mgroup3ParserData::decode(bytes.as_slice()) {
        Ok(d) => d,
        Err(e) => {
            failures.push(format!(
                "{}: decode data.pb failed: {}",
                case_dir.display(),
                e
            ));
            return failures;
        }
    };
    let parser = Mgroup3Parser::new(data);
    let inputs_dir = case_dir.join("inputs");
    let mut entries: Vec<PathBuf> = fs::read_dir(&inputs_dir)
        .unwrap_or_else(|e| panic!("read_dir {}: {}", inputs_dir.display(), e))
        .filter_map(|e| e.ok().map(|e| e.path()))
        .collect();
    entries.sort();
    for input_dir in entries {
        if !input_dir.is_dir() {
            continue;
        }
        let input_path = input_dir.join("input.txt");
        let golden_path = input_dir.join("golden.txt");
        let input = fs::read_to_string(&input_path)
            .unwrap_or_else(|e| panic!("read {}: {}", input_path.display(), e));
        let golden = fs::read_to_string(&golden_path)
            .unwrap_or_else(|e| panic!("read {}: {}", golden_path.display(), e));

        let actual = match parser.parse(&input) {
            Ok(ctx) => {
                if parser.is_accepted(&ctx) {
                    serialize_kernels_history(&parser.kernels_history(&ctx))
                } else {
                    "REJECTED\n".to_string()
                }
            }
            Err(ParsingError::UnexpectedInput { .. } | ParsingError::UnexpectedEof { .. }) => {
                "REJECTED\n".to_string()
            }
        };

        if actual != golden {
            failures.push(format!(
                "{}\n  input={:?}\n  expected:\n{}\n  actual:\n{}",
                input_dir.display(),
                input,
                indent(&golden, "    "),
                indent(&actual, "    ")
            ));
        }
    }
    failures
}

fn indent(s: &str, prefix: &str) -> String {
    let mut out = String::new();
    for line in s.lines() {
        out.push_str(prefix);
        out.push_str(line);
        out.push('\n');
    }
    out
}

#[test]
fn diff_against_kotlin_parser_fixture() {
    let committed = committed_fixtures_root();
    let generated = generated_fixtures_root();
    assert!(
        committed.exists(),
        "committed fixture dir {} missing — run `bibix4 runMgroup3Test` to regenerate",
        committed.display()
    );

    let mut case_dirs: Vec<PathBuf> = Vec::new();
    for root in [&committed, &generated] {
        if !root.exists() {
            continue;
        }
        case_dirs.extend(
            fs::read_dir(root)
                .unwrap_or_else(|e| panic!("read_dir {}: {}", root.display(), e))
                .filter_map(|e| e.ok().map(|e| e.path()))
                .filter(|p| p.is_dir()),
        );
    }
    case_dirs.sort();
    assert!(!case_dirs.is_empty(), "no fixture cases under {} or {}", committed.display(), generated.display());

    if !generated.exists() || fs::read_dir(&generated).map(|it| it.count()).unwrap_or(0) == 0 {
        eprintln!(
            "note: {} is empty — large grammar cases (e.g. mulang) are skipped. \
             Run `bibix4 runMgroup3Test` to populate.",
            generated.display()
        );
    }

    let mut total_inputs = 0usize;
    let mut all_failures: Vec<String> = Vec::new();
    let mut case_summary: Vec<(String, usize, usize)> = Vec::new(); // (name, ok, fail)
    for case_dir in &case_dirs {
        let case_name = case_dir.file_name().unwrap().to_string_lossy().into_owned();
        let before = all_failures.len();
        let failures = run_case(case_dir);
        let inputs_dir = case_dir.join("inputs");
        let n_inputs = fs::read_dir(&inputs_dir)
            .map(|it| it.filter_map(|e| e.ok()).filter(|e| e.path().is_dir()).count())
            .unwrap_or(0);
        total_inputs += n_inputs;
        let fail_count = failures.len();
        let ok_count = n_inputs - fail_count;
        all_failures.extend(failures);
        case_summary.push((case_name, ok_count, fail_count));
        let _ = before;
    }

    println!(
        "parser_diff: {} cases / {} inputs total",
        case_dirs.len(),
        total_inputs
    );
    for (name, ok, fail) in &case_summary {
        if *fail == 0 {
            println!("  {}: {} ok", name, ok);
        } else {
            println!("  {}: {} ok / {} FAIL", name, ok, fail);
        }
    }

    if !all_failures.is_empty() {
        let n = all_failures.len();
        for f in &all_failures {
            eprintln!("--- FAIL ---\n{}", f);
        }
        panic!("{} input(s) diverged from Kotlin golden", n);
    }
}
