package com.giyeok.jparser.mgroup3

import com.giyeok.jparser.metalang3.MetaLanguage3.ProcessedGrammar
import com.giyeok.jparser.metalang3.Type
import com.giyeok.jparser.metalang3.codegen.KotlinOptCodeGen
import java.nio.file.Path
import kotlin.io.path.createDirectories
import kotlin.io.path.writeText

/**
 * Kotlin 측 산출물 emit:
 *   - `<className>.kt` — typed AST + kernels_history walk (KotlinOptCodeGen)
 *   - `<className>ProtoBinding.kt` — ID-based proto `ParseResult` ↔ typed AST
 *     양방향 변환 (decode: byId map + 재귀 reconstruct, encode: Rust encode.rs
 *     와 동일한 순회/ID 할당 규약 — 자식 먼저 encode 후 부모 id 할당, 1부터 단조 증가).
 *
 * Binding 은 proto java 클래스(Stage2ProtoEmit 의 ast.proto 를 protoc 로 컴파일,
 * `java_multiple_files = true`)가 classpath 에 있어야 컴파일된다. proto package 의
 * 클래스들은 import alias (`P<Name>`) 로 참조해 typed AST 클래스명과의 충돌을 피한다.
 */
object Stage3KotlinEmit {
  fun run(
    processed: ProcessedGrammar,
    schema: AstSchema,
    outDir: Path,
    className: String = "Ast",
    pkg: String = "com.giyeok.jparser.mgroup3.generated",
  ) {
    val codegen = KotlinOptCodeGen(processed)
    val src = codegen.generate(className, pkg)
    val pkgDir = outDir.resolve(pkg.replace('.', '/'))
    pkgDir.createDirectories()
    pkgDir.resolve("$className.kt").writeText(src)
    pkgDir.resolve("${className}ProtoBinding.kt")
      .writeText(binding(processed, schema, className, pkg))
  }

  private fun rootClassName(processed: ProcessedGrammar): String {
    val rootType = processed.nonterminalTypes().apply(processed.startNonterminalName())
    require(rootType is Type.ClassType) {
      "start symbol type is not a class: $rootType — proto binding 은 클래스 루트만 지원"
    }
    return rootType.name()
  }

  private fun binding(
    processed: ProcessedGrammar,
    schema: AstSchema,
    className: String,
    pkg: String,
  ): String {
    val concretes = schema.messages.filter { it.sealedChildren.isEmpty() }
    val sealeds = schema.messages.filter { it.sealedChildren.isNotEmpty() }
    // schema(proto/Rust) 이름 → Kotlin AST 원본 이름 (Self → SelfNode 류 역매핑).
    val kotlinNames: Map<String, String> =
      schema.messages.associate { it.name to it.kotlinName } +
        schema.enums.associate { it.name to it.kotlinName }
    val root = rootClassName(processed)
    val rootSchemaName = SchemaBuilder.rustSafeName(root)

    val sb = StringBuilder()
    sb.append("package $pkg\n\n")
    sb.append("// Generated by Stage3KotlinEmit — do not edit by hand.\n")
    sb.append("// ID-based proto ParseResult ↔ typed AST. See phase_b_proto_design.md.\n\n")
    // proto 클래스들은 alias 로 — typed AST 의 nested 클래스명과 충돌 방지.
    sb.append("import ${schema.packageName}.NodeEntry as PNodeEntry\n")
    sb.append("import ${schema.packageName}.ParseResult as PParseResult\n")
    for (m in concretes.sortedBy { it.name }) {
      sb.append("import ${schema.packageName}.${m.name} as P${m.name}\n")
    }
    for (e in schema.enums.sortedBy { it.name }) {
      sb.append("import ${schema.packageName}.${e.name} as P${e.name}\n")
    }
    sb.append("\n")
    sb.append("object ${className}ProtoBinding {\n")

    // ---- decode ----
    sb.append(
      """
      |  fun fromProtoBytes(bytes: ByteArray): $className.$root =
      |    fromProto(PParseResult.parseFrom(bytes))
      |
      |  fun fromProto(result: PParseResult): $className.$root =
      |    Decoder(result).node(result.rootId) as $className.$root
      |
      |  private class Decoder(result: PParseResult) {
      |    private val byId: Map<Int, PNodeEntry> = result.nodesList.associateBy { it.id }
      |    private val memo = HashMap<Int, $className.AstNode>()
      |
      |    fun node(id: Int): $className.AstNode = memo.getOrPut(id) {
      |      val entry = byId[id] ?: error("ParseResult: missing node id=${'$'}id")
      |      when (entry.nodeCase) {
      |
      """.trimMargin()
    )
    for (m in concretes.sortedBy { it.name }) {
      sb.append("        PNodeEntry.NodeCase.${screamingSnake(m.name)} -> decode${m.name}(id, entry.${lowerCamel(m.name)})\n")
    }
    sb.append("        else -> error(\"ParseResult: node id=\$id has empty oneof\")\n")
    sb.append("      }\n    }\n\n")

    for (m in concretes) {
      sb.append(decodeFn(className, m, kotlinNames))
      sb.append("\n")
    }
    sb.append("  }\n\n")

    // ---- encode ----
    sb.append(
      """
      |  fun toProtoBytes(root: $className.$root): ByteArray = toProto(root).toByteArray()
      |
      |  fun toProto(root: $className.$root): PParseResult {
      |    val enc = Encoder()
      |    val rootId = enc.encode$rootSchemaName(root)
      |    return PParseResult.newBuilder().setRootId(rootId).addAllNodes(enc.nodes).build()
      |  }
      |
      |  private class Encoder {
      |    val nodes = ArrayList<PNodeEntry>()
      |    private var nextId = 1
      |    private fun alloc(): Int = nextId++
      |
      |
      """.trimMargin()
    )
    for (m in concretes) {
      sb.append(encodeFn(className, m, kotlinNames))
      sb.append("\n")
    }
    for (m in sealeds) {
      sb.append("    fun encode${m.name}(node: $className.${m.kotlinName}): Int = when (node) {\n")
      for (child in m.sealedChildren.sorted()) {
        sb.append("      is $className.${kotlinNames[child] ?: child} -> encode$child(node)\n")
      }
      sb.append("    }\n\n")
    }
    sb.append("  }\n")
    sb.append("}\n")
    return sb.toString()
  }

  // --- decode fn for one concrete message --------------------------------

  private fun decodeFn(className: String, m: MessageDef, kotlinNames: Map<String, String>): String {
    val sb = StringBuilder()
    sb.append("    private fun decode${m.name}(id: Int, m: P${m.name}): $className.${m.kotlinName} =\n")
    sb.append("      $className.${m.kotlinName}(\n")
    for (f in m.fields) {
      sb.append("        ${f.name} = ${decodeExpr(className, f.name, f.type, kotlinNames)},\n")
    }
    sb.append("        nodeId = id,\n")
    sb.append("        start = m.start,\n")
    sb.append("        end = m.end,\n")
    sb.append("      )\n")
    return sb.toString()
  }

  /** proto getter → Kotlin 값 식. `name` 은 camelCase (proto java getter 와 일치). */
  private fun decodeExpr(className: String, name: String, t: SchemaType, kn: Map<String, String>): String = when (t) {
    SchemaType.Bool, SchemaType.Int32, SchemaType.Str -> "m.$name"
    SchemaType.NodeBytes ->
      error("NodeBytes 는 Kotlin binding 에서 아직 미지원 (field $name)")
    is SchemaType.Enm -> "$className.${kn[t.name] ?: t.name}.valueOf(${stripEnumPrefix(t.name, "m.$name.name")})"
    is SchemaType.Msg -> "node(m.$name) as $className.${kn[t.name] ?: t.name}"
    is SchemaType.Arr -> decodeArrExpr(className, name, t.of, kn)
    is SchemaType.Opt -> when (val inner = t.of) {
      is SchemaType.Arr ->
        "if (m.${name}Present) ${decodeArrExpr(className, name, inner.of, kn)} else null"
      is SchemaType.Msg ->
        "if (m.${name}Present) node(m.$name) as $className.${kn[inner.name] ?: inner.name} else null"
      is SchemaType.Enm ->
        "if (m.${name}Present) $className.${kn[inner.name] ?: inner.name}.valueOf(${stripEnumPrefix(inner.name, "m.$name.name")}) else null"
      SchemaType.Bool, SchemaType.Int32, SchemaType.Str ->
        "if (m.${name}Present) m.$name else null"
      else -> error("unsupported Opt inner type for field $name: $inner")
    }
  }

  private fun decodeArrExpr(className: String, name: String, elem: SchemaType, kn: Map<String, String>): String =
    when (elem) {
      is SchemaType.Msg -> "m.${name}List.map { node(it) as $className.${kn[elem.name] ?: elem.name} }"
      is SchemaType.Enm -> "m.${name}List.map { $className.${kn[elem.name] ?: elem.name}.valueOf(${stripEnumPrefix(elem.name, "it.name")}) }"
      SchemaType.Bool -> "m.${name}List.toList()"
      SchemaType.Int32 -> "m.${name}List.map { it.toInt() }"
      SchemaType.Str -> "m.${name}List.toList()"
      else -> error("unsupported Arr element type for field $name: $elem")
    }

  // --- encode fn for one concrete message --------------------------------

  private fun encodeFn(className: String, m: MessageDef, kn: Map<String, String>): String {
    val sb = StringBuilder()
    sb.append("    fun encode${m.name}(node: $className.${m.kotlinName}): Int {\n")
    // 자식 먼저 encode (Rust encoder 와 동일한 ID 할당 순서: 자식 id < 부모 id).
    val setters = mutableListOf<String>()
    for (f in m.fields) {
      encodeField(sb, setters, f, kn)
    }
    sb.append("      val id = alloc()\n")
    sb.append("      nodes.add(\n")
    sb.append("        PNodeEntry.newBuilder().setId(id).set${m.name}(\n")
    sb.append("          P${m.name}.newBuilder()\n")
    for (s in setters) {
      sb.append("            $s\n")
    }
    sb.append("            .setStart(node.start)\n")
    sb.append("            .setEnd(node.end)\n")
    sb.append("            .build()\n")
    sb.append("        ).build()\n")
    sb.append("      )\n")
    sb.append("      return id\n")
    sb.append("    }\n")
    return sb.toString()
  }

  private fun encodeField(
    sb: StringBuilder,
    setters: MutableList<String>,
    f: FieldDef,
    kn: Map<String, String>,
  ) {
    val name = f.name
    val cap = name.replaceFirstChar { it.uppercaseChar() }
    when (val t = f.type) {
      SchemaType.Bool, SchemaType.Int32, SchemaType.Str ->
        setters.add(".set$cap(node.$name)")
      SchemaType.NodeBytes ->
        error("NodeBytes 는 Kotlin binding 에서 아직 미지원 (field $name)")
      is SchemaType.Enm ->
        setters.add(".set$cap(P${t.name}.valueOf(${addEnumPrefix(t.name, "node.$name.name")}))")
      is SchemaType.Msg -> {
        sb.append("      val ${name}Id = encode${t.name}(node.$name)\n")
        setters.add(".set$cap(${name}Id)")
      }
      is SchemaType.Arr -> {
        sb.append("      val ${name}Vals = ${encodeArrExprOn("node.$name", t.of, kn)}\n")
        setters.add(".addAll$cap(${name}Vals)")
      }
      is SchemaType.Opt -> when (val inner = t.of) {
        is SchemaType.Msg -> {
          sb.append("      val ${name}Id = node.$name?.let { encode${inner.name}(it) } ?: 0\n")
          setters.add(".set${cap}Present(node.$name != null)")
          setters.add(".set$cap(${name}Id)")
        }
        is SchemaType.Arr -> {
          sb.append("      val ${name}Vals = node.$name?.let { xs -> ${encodeArrExprOn("xs", inner.of, kn)} } ?: emptyList()\n")
          setters.add(".set${cap}Present(node.$name != null)")
          setters.add(".addAll$cap(${name}Vals)")
        }
        is SchemaType.Enm -> {
          setters.add(".set${cap}Present(node.$name != null)")
          setters.add(".set$cap(node.$name?.let { P${inner.name}.valueOf(${addEnumPrefix(inner.name, "it.name")}) } ?: P${inner.name}.forNumber(0))")
        }
        SchemaType.Str -> {
          setters.add(".set${cap}Present(node.$name != null)")
          setters.add(".set$cap(node.$name ?: \"\")")
        }
        SchemaType.Int32 -> {
          setters.add(".set${cap}Present(node.$name != null)")
          setters.add(".set$cap(node.$name ?: 0)")
        }
        SchemaType.Bool -> {
          setters.add(".set${cap}Present(node.$name != null)")
          setters.add(".set$cap(node.$name ?: false)")
        }
        else -> error("unsupported Opt inner type for field $name: $inner")
      }
    }
  }

  private fun encodeArrExprOn(receiver: String, elem: SchemaType, kn: Map<String, String>): String = when (elem) {
    is SchemaType.Msg -> "$receiver.map { encode${elem.name}(it) }"
    is SchemaType.Enm -> "$receiver.map { P${elem.name}.valueOf(${addEnumPrefix(elem.name, "it.name")}) }"
    SchemaType.Bool, SchemaType.Int32, SchemaType.Str -> receiver
    else -> error("unsupported Arr element type: $elem")
  }

  // --- name munging -------------------------------------------------------

  // proto enum 값은 `<ENUM_NAME>_<VALUE>` 로 prefix 됨 (Stage2ProtoEmit) —
  // Kotlin enum 이름과 오갈 때 prefix 를 더하고/벗긴다.
  private fun stripEnumPrefix(enumName: String, expr: String): String =
    "$expr.removePrefix(\"" + screamingSnake(enumName) + "_\")"

  private fun addEnumPrefix(enumName: String, expr: String): String =
    "\"" + screamingSnake(enumName) + "_\" + " + expr

  /** `ModuleDef` → `MODULE_DEF` (NodeEntry oneof case 상수). */
  private fun screamingSnake(s: String): String {
    val sb = StringBuilder()
    for ((i, c) in s.withIndex()) {
      if (c.isUpperCase()) {
        if (i > 0) sb.append('_')
        sb.append(c)
      } else {
        sb.append(c.uppercaseChar())
      }
    }
    return sb.toString()
  }

  /** `ModuleDef` → `moduleDef` (NodeEntry oneof getter). */
  private fun lowerCamel(s: String): String = s.replaceFirstChar { it.lowercaseChar() }
}
