package com.giyeok.jparser.mgroup3

import com.giyeok.jparser.metalang3.MetaLanguage3.ProcessedGrammar
import com.giyeok.jparser.metalang3.codegen.RustOptCodeGen
import java.nio.file.Path
import kotlin.io.path.createDirectories
import kotlin.io.path.writeText

/**
 * Emits a per-grammar Rust crate that walks `kernels_history` into a typed AST
 * and encodes it to the ID-based proto `ParseResult`.
 *
 * DRAFT. The walk + encoder code is produced by [[RustOptCodeGen]] (Scala,
 * under metalang3) — the same way [[Stage3KotlinEmit]] delegates to
 * `KotlinOptCodeGen`. This stage only lays out the crate skeleton and the
 * static `ktlib.rs` support module.
 *
 * Crate layout:
 *   <rustDir>/
 *     Cargo.toml
 *     build.rs                 # prost-build over proto/ast.proto
 *     proto/ast.proto          # Stage2ProtoEmit (ID-based schema)
 *     src/lib.rs               # module tree + `pub mod proto { include!(...) }`
 *     src/ktlib.rs             # KernelSet + AstifierUtil port (static)
 *     src/ast.rs               # AST types + walk (RustOptCodeGen.generate)
 *     src/encode.rs            # typed AST -> proto (RustOptCodeGen.generateEncoder)
 *
 * The `ktlib.rs` content is currently embedded here. TODO: move it into
 * `mgroup3-native` (or a dedicated `mgroup3-ktlib` crate) so generated crates
 * depend on it rather than each carrying a copy.
 */
object Stage4RustEmit {
  fun run(
    processed: ProcessedGrammar,
    schema: AstSchema,
    rustDir: Path,
    mgroup3NativePath: String,
  ) {
    rustDir.createDirectories()
    val protoDir = rustDir.resolve("proto").also { it.createDirectories() }
    val srcDir = rustDir.resolve("src").also { it.createDirectories() }

    val codegen = RustOptCodeGen(processed)
    val astRs = codegen.generate()
    // generate() populates symbolsOfInterest etc. as a side effect; the encoder
    // only needs the class hierarchy, so order between the two does not matter.
    val encodeRs = codegen.generateEncoder()

    protoDir.resolve("ast.proto").writeText(Stage2ProtoEmit.emit(schema))
    rustDir.resolve("Cargo.toml").writeText(cargoToml(mgroup3NativePath))
    rustDir.resolve("build.rs").writeText(buildRs())
    srcDir.resolve("lib.rs").writeText(libRs(schema))
    srcDir.resolve("ktlib.rs").writeText(KTLIB_RS)
    srcDir.resolve("ast.rs").writeText(astRs)
    srcDir.resolve("encode.rs").writeText(encodeRs)
  }

  private fun cargoToml(mgroup3NativePath: String): String = """
    |[package]
    |name = "mgroup3-generated-parser"
    |version = "0.1.0"
    |edition = "2021"
    |
    |[dependencies]
    |prost = "0.14"
    |bytes = "1"
    |# TODO: depend on mgroup3-native for the real Mgroup3Parser + KernelSet once
    |# ktlib.rs graduates there. For now the crate is self-contained.
    |# mgroup3-native = { path = "$mgroup3NativePath" }
    |
    |[build-dependencies]
    |prost-build = "0.14"
    |""".trimMargin()

  private fun buildRs(): String = """
    |use std::io::Result;
    |
    |fn main() -> Result<()> {
    |    prost_build::compile_protos(&["proto/ast.proto"], &["proto"])?;
    |    Ok(())
    |}
    |""".trimMargin()

  private fun libRs(schema: AstSchema): String = """
    |// Generated by GenCli — do not edit by hand.
    |
    |pub mod ktlib;
    |pub mod ast;
    |pub mod encode;
    |
    |pub mod proto {
    |    include!(concat!(env!("OUT_DIR"), "/${schema.packageName}.rs"));
    |}
    |""".trimMargin()

  /**
   * Static support module: Rust port of `com.giyeok.jparser.ktlib.{Kernel,
   * KernelSet}` + `AstifierUtil`. Kept in sync with
   * examples/generated/rust/ktlib_ast/mod.rs.
   */
  private val KTLIB_RS: String = """
    |// Generated (static) by Stage4RustEmit. Port of ktlib + AstifierUtil.
    |// TODO: move into mgroup3-native and depend on it instead of copying.
    |
    |use std::collections::HashSet;
    |
    |#[derive(Copy, Clone, PartialEq, Eq, Hash, Debug)]
    |pub struct Kernel {
    |    pub symbol_id: i32,
    |    pub pointer: i32,
    |    pub begin_gen: i32,
    |    pub end_gen: i32,
    |}
    |
    |#[derive(Clone, Debug, Default)]
    |pub struct KernelSet {
    |    pub kernels: HashSet<Kernel>,
    |}
    |
    |impl KernelSet {
    |    pub fn new(kernels: HashSet<Kernel>) -> Self {
    |        Self { kernels }
    |    }
    |
    |    pub fn contains(&self, kernel: &Kernel) -> bool {
    |        self.kernels.contains(kernel)
    |    }
    |
    |    pub fn filter_by_begin_gen(&self, symbol_id: i32, pointer: i32, begin_gen: i32) -> Vec<Kernel> {
    |        self.kernels
    |            .iter()
    |            .filter(|k| k.symbol_id == symbol_id && k.pointer == pointer && k.begin_gen == begin_gen)
    |            .copied()
    |            .collect()
    |    }
    |
    |    pub fn find_by_begin_gen(&self, symbol_id: i32, pointer: i32, begin_gen: i32) -> Kernel {
    |        let matches = self.filter_by_begin_gen(symbol_id, pointer, begin_gen);
    |        check_single(&matches);
    |        matches[0]
    |    }
    |
    |    pub fn find_by_begin_gen_opt(&self, symbol_id: i32, pointer: i32, begin_gen: i32) -> Option<Kernel> {
    |        let matches = self.filter_by_begin_gen(symbol_id, pointer, begin_gen);
    |        check_single_or_none(&matches);
    |        matches.into_iter().next()
    |    }
    |
    |    pub fn get_single(&self, symbol_id: i32, pointer: i32, begin_gen: i32, end_gen: i32) -> Kernel {
    |        self.kernels
    |            .iter()
    |            .copied()
    |            .find(|k| {
    |                k.symbol_id == symbol_id
    |                    && k.pointer == pointer
    |                    && k.begin_gen == begin_gen
    |                    && k.end_gen == end_gen
    |            })
    |            .unwrap_or_else(|| panic!("no kernel at ({}, {}, {}..{}) in set", symbol_id, pointer, begin_gen, end_gen))
    |    }
    |}
    |
    |fn check_single<T>(xs: &[T]) {
    |    assert_eq!(xs.len(), 1, "Kernel size was expected to be 1, but it was {}", xs.len());
    |}
    |
    |fn check_single_or_none<T>(xs: &[T]) {
    |    assert!(xs.len() <= 1, "Kernel size was expected to be <= 1, was {}", xs.len());
    |}
    |
    |pub fn has_single_true(bs: &[bool]) -> bool {
    |    bs.iter().filter(|b| **b).count() == 1
    |}
    |
    |pub type GenSpan = (i32, i32);
    |
    |pub fn get_sequence_elems(
    |    history: &[KernelSet],
    |    sequence_id: i32,
    |    elems: &[i32],
    |    begin_gen: i32,
    |    end_gen: i32,
    |) -> Vec<GenSpan> {
    |    let n = elems.len();
    |    let last_elem = history[end_gen as usize].find_by_begin_gen(sequence_id, n as i32, begin_gen);
    |    let mut list = vec![last_elem];
    |    let mut curr_gen = last_elem.end_gen;
    |    for pointer in (0..n).rev() {
    |        let candidates =
    |            history[curr_gen as usize].filter_by_begin_gen(sequence_id, pointer as i32, begin_gen);
    |        let curr_gen_snapshot = curr_gen;
    |        let filtered: Vec<Kernel> = candidates
    |            .into_iter()
    |            .filter(|prev| {
    |                history[curr_gen_snapshot as usize].contains(&Kernel {
    |                    symbol_id: elems[pointer],
    |                    pointer: 1,
    |                    begin_gen: prev.end_gen,
    |                    end_gen: curr_gen_snapshot,
    |                })
    |            })
    |            .collect();
    |        check_single(&filtered);
    |        let prev_elem = filtered[0];
    |        list.push(prev_elem);
    |        curr_gen = prev_elem.end_gen;
    |    }
    |    (0..n).map(|i| (list[n - i].end_gen, list[n - i - 1].end_gen)).collect()
    |}
    |
    |pub fn unroll_repeat0(
    |    history: &[KernelSet],
    |    symbol_id: i32,
    |    item_sym_id: i32,
    |    base_seq: i32,
    |    repeat_seq: i32,
    |    begin_gen: i32,
    |    end_gen: i32,
    |) -> Vec<GenSpan> {
    |    let mut acc: Vec<GenSpan> = Vec::new();
    |    let mut bg = begin_gen;
    |    let mut eg = end_gen;
    |    loop {
    |        let base = history[eg as usize].find_by_begin_gen_opt(base_seq, 0, bg);
    |        let repeat = history[eg as usize].find_by_begin_gen_opt(repeat_seq, 2, bg);
    |        assert!(has_single_true(&[base.is_some(), repeat.is_some()]));
    |        if base.is_some() {
    |            return acc;
    |        }
    |        let seq = get_sequence_elems(history, repeat_seq, &[symbol_id, item_sym_id], bg, eg);
    |        let repeating = seq[0];
    |        let item = seq[1];
    |        acc.insert(0, item);
    |        bg = repeating.0;
    |        eg = repeating.1;
    |    }
    |}
    |
    |pub fn unroll_repeat1(
    |    history: &[KernelSet],
    |    symbol_id: i32,
    |    item_sym_id: i32,
    |    base_seq: i32,
    |    repeat_seq: i32,
    |    begin_gen: i32,
    |    end_gen: i32,
    |) -> Vec<GenSpan> {
    |    let mut acc: Vec<GenSpan> = Vec::new();
    |    let mut bg = begin_gen;
    |    let mut eg = end_gen;
    |    loop {
    |        let base = history[eg as usize].find_by_begin_gen_opt(base_seq, 1, bg);
    |        let repeat = history[eg as usize].find_by_begin_gen_opt(repeat_seq, 2, bg);
    |        assert!(has_single_true(&[base.is_some(), repeat.is_some()]));
    |        if base.is_some() {
    |            let base_item = history[eg as usize].find_by_begin_gen(item_sym_id, 1, bg);
    |            acc.insert(0, (base_item.begin_gen, base_item.end_gen));
    |            return acc;
    |        }
    |        let seq = get_sequence_elems(history, repeat_seq, &[symbol_id, item_sym_id], bg, eg);
    |        let repeating = seq[0];
    |        let item = seq[1];
    |        acc.insert(0, item);
    |        bg = repeating.0;
    |        eg = repeating.1;
    |    }
    |}
    |
    |pub struct IdIssuer {
    |    next: i32,
    |}
    |
    |impl IdIssuer {
    |    pub fn new(start: i32) -> Self {
    |        Self { next: start }
    |    }
    |    pub fn next_id(&mut self) -> i32 {
    |        let id = self.next;
    |        self.next += 1;
    |        id
    |    }
    |}
    |""".trimMargin()
}
