package com.giyeok.jparser.mgroup3

import java.nio.file.Path
import kotlin.io.path.createDirectories
import kotlin.io.path.writeText

/**
 * Emits a per-grammar `.proto` schema following the ID-based design.
 *
 * See `mgroup3/docs/phase_b_proto_design.md` for the rationale and the
 * full emit rules. Quick summary:
 *
 *   - Every concrete node becomes a flat message. Cross-node references are
 *     `int32` ids that resolve into `ParseResult.nodes`.
 *   - Sealed parents are NOT emitted. Their dispatch is recovered by the
 *     consumer from `NodeEntry.node` (the oneof case).
 *   - Per-message field numbers: grammar payload starts at 1; `start` is
 *     always tag 100 and `end` is always tag 101.
 *   - Always-trailing envelope: `NodeEntry { id; oneof node { ... } }` and
 *     `ParseResult { root_id; repeated NodeEntry nodes }`. NodeEntry oneof
 *     tags start at 10 and follow alphabetical order of message names for
 *     stability across regenerations.
 *
 *   - `Opt(scalar)`, `Opt(Msg)`, `Opt(Arr(T))` are split into two fields:
 *     `<name>_present` (bool) + `<name>[_value]` (payload). Uniform decode
 *     logic regardless of inner type. See design doc for why.
 *
 * The emitter does not perform SCC analysis, multi-superclass disambiguation,
 * or active-parent extraction. All those problems are addressed by the ID
 * indirection.
 */
object Stage2ProtoEmit {
  private const val START_FIELD_TAG = 100
  private const val END_FIELD_TAG = 101
  private const val NODE_ENTRY_ONEOF_START_TAG = 10

  fun emit(schema: AstSchema): String {
    val sb = StringBuilder()
    sb.append("// Generated by Stage2ProtoEmit — do not edit by hand.\n")
    sb.append("// See mgroup3/docs/phase_b_proto_design.md.\n\n")
    sb.append("syntax = \"proto3\";\n\n")
    sb.append("package ").append(schema.packageName).append(";\n\n")
    // Kotlin/Java 측 binding 이 top-level 클래스로 참조할 수 있도록.
    // prost(Rust) 는 java option 을 무시하므로 Rust 출력엔 영향 없음.
    sb.append("option java_multiple_files = true;\n\n")

    for (e in schema.enums) {
      emitEnum(sb, e)
    }

    val concrete = schema.messages.filter { it.sealedChildren.isEmpty() }
    for (m in concrete) {
      emitMessage(sb, m)
    }

    emitNodeEntry(sb, concrete)
    emitParseResult(sb)
    return sb.toString()
  }

  fun run(schema: AstSchema, out: Path) {
    out.parent?.createDirectories()
    out.writeText(emit(schema))
  }

  // --- enum --------------------------------------------------------------

  private fun emitEnum(sb: StringBuilder, e: EnumDef) {
    sb.append("enum ").append(e.name).append(" {\n")
    sb.append("  ").append(screamingSnake(e.name)).append("_UNSPECIFIED = 0;\n")
    e.values.forEachIndexed { i, v ->
      sb.append("  ").append(v).append(" = ").append(i + 1).append(";\n")
    }
    sb.append("}\n\n")
  }

  // --- concrete message --------------------------------------------------

  private fun emitMessage(sb: StringBuilder, m: MessageDef) {
    sb.append("message ").append(m.name).append(" {\n")
    var nextTag = 1
    for (f in m.fields) {
      nextTag = emitField(sb, f, nextTag)
    }
    sb.append("  int32 start = ").append(START_FIELD_TAG).append(";\n")
    sb.append("  int32 end = ").append(END_FIELD_TAG).append(";\n")
    sb.append("}\n\n")
  }

  /**
   * Emit a single logical field, returning the next free tag.
   * Optional fields (including `Opt(Arr)`) take two contiguous tags so the
   * `<name>_present` + `<name>` split shares ordering with the source field.
   */
  private fun emitField(sb: StringBuilder, f: FieldDef, startTag: Int): Int {
    val t = f.type
    // proto3 style guide: field names are snake_case. The AST schema carries
    // Kotlin/Scala camelCase identifiers, so convert here.
    val name = snakeCase(f.name)
    return when (t) {
      is SchemaType.Opt -> emitOptionalField(sb, name, t.of, startTag)
      is SchemaType.Arr -> {
        // `repeated <T> <name>;` — proto3 distinguishes absent vs empty only
        // when wrapped in Opt. Bare Arr always becomes `repeated`.
        val (label, typeStr) = "repeated" to typeNameForRef(t.of)
        sb.append("  ").append(label).append(" ").append(typeStr)
          .append(" ").append(name).append(" = ").append(startTag).append(";\n")
        startTag + 1
      }
      else -> {
        sb.append("  ").append(typeNameForRef(t)).append(" ").append(name)
          .append(" = ").append(startTag).append(";\n")
        startTag + 1
      }
    }
  }

  /**
   * `Opt(X)` always splits into `bool <name>_present = N; <X> <name> = N+1;`
   * for scalars/messages/enums, or `bool <name>_present = N; repeated <T> <name> = N+1;`
   * for `Opt(Arr(T))`. Keeps decode logic uniform.
   *
   * `name` is expected to already be snake_case (the caller converts).
   */
  private fun emitOptionalField(
    sb: StringBuilder,
    name: String,
    inner: SchemaType,
    startTag: Int,
  ): Int {
    sb.append("  bool ").append(name).append("_present = ").append(startTag).append(";\n")
    when (inner) {
      is SchemaType.Arr -> {
        sb.append("  repeated ").append(typeNameForRef(inner.of))
          .append(" ").append(name).append(" = ").append(startTag + 1).append(";\n")
      }
      is SchemaType.Opt -> {
        // Nested optional collapses (no use case in current grammars; treat
        // as the inner Opt). Emit a comment so this is visible if it ever
        // happens, then recurse for the second slot.
        sb.append("  // note: nested Opt collapsed at codegen.\n")
        sb.append("  ").append(typeNameForRef(inner.of)).append(" ").append(name)
          .append(" = ").append(startTag + 1).append(";\n")
      }
      else -> {
        sb.append("  ").append(typeNameForRef(inner)).append(" ").append(name)
          .append(" = ").append(startTag + 1).append(";\n")
      }
    }
    return startTag + 2
  }

  // --- envelope ----------------------------------------------------------

  private fun emitNodeEntry(sb: StringBuilder, concrete: List<MessageDef>) {
    sb.append("message NodeEntry {\n")
    sb.append("  int32 id = 1;\n")
    sb.append("  oneof node {\n")
    // Alphabetical for stable tag assignment. Tags start at NODE_ENTRY_ONEOF_START_TAG.
    val sorted = concrete.sortedBy { it.name }
    sorted.forEachIndexed { i, m ->
      sb.append("    ").append(m.name).append(" ").append(snakeCase(m.name))
        .append(" = ").append(NODE_ENTRY_ONEOF_START_TAG + i).append(";\n")
    }
    sb.append("  }\n")
    sb.append("}\n\n")
  }

  private fun emitParseResult(sb: StringBuilder) {
    sb.append("message ParseResult {\n")
    sb.append("  int32 root_id = 1;\n")
    sb.append("  repeated NodeEntry nodes = 2;\n")
    sb.append("}\n")
  }

  // --- type rendering ----------------------------------------------------

  /**
   * Renders a `SchemaType` as it appears at a reference site — i.e. on the
   * right-hand side of a proto field declaration. `Msg` collapses to `int32`
   * because all cross-node references go through `NodeEntry.id`.
   *
   * Should not be called on `Opt` or `Arr` directly — those are handled in
   * `emitField` / `emitOptionalField` where the field declaration is built.
   */
  private fun typeNameForRef(t: SchemaType): String = when (t) {
    SchemaType.Bool -> "bool"
    SchemaType.Int32 -> "int32"
    SchemaType.Str -> "string"
    SchemaType.NodeBytes -> "bytes"
    is SchemaType.Msg -> "int32"
    is SchemaType.Enm -> t.name
    is SchemaType.Opt -> error("Opt should be handled by emitOptionalField, not here")
    is SchemaType.Arr -> error("Arr should be handled by emitField, not here")
  }

  // --- name munging ------------------------------------------------------

  /** `ModuleDef` → `module_def`, used for NodeEntry oneof field names. */
  private fun snakeCase(s: String): String {
    val sb = StringBuilder()
    for ((i, c) in s.withIndex()) {
      if (c.isUpperCase()) {
        if (i > 0) sb.append('_')
        sb.append(c.lowercaseChar())
      } else {
        sb.append(c)
      }
    }
    return sb.toString()
  }

  /** `TypeAttr` → `TYPE_ATTR`, used for enum's UNSPECIFIED prefix. */
  private fun screamingSnake(s: String): String = snakeCase(s).uppercase()
}
