package com.giyeok.jparser.mgroup3

import java.nio.file.Path
import kotlin.io.path.createDirectories
import kotlin.io.path.writeText

object Stage4RustEmit {
  fun run(schema: AstSchema, rustDir: Path, mgroup3NativePath: String) {
    rustDir.createDirectories()
    val protoDir = rustDir.resolve("proto").also { it.createDirectories() }
    val srcDir = rustDir.resolve("src").also { it.createDirectories() }

    protoDir.resolve("ast.proto").writeText(Stage2ProtoEmit.emit(schema))
    rustDir.resolve("Cargo.toml").writeText(cargoToml(mgroup3NativePath))
    rustDir.resolve("build.rs").writeText(buildRs())
    srcDir.resolve("lib.rs").writeText(libRs(schema))
  }

  private fun cargoToml(mgroup3NativePath: String): String = """
    |[package]
    |name = "mgroup3-generated-parser"
    |version = "0.1.0"
    |edition = "2021"
    |
    |[dependencies]
    |prost = "0.14"
    |bytes = "1"
    |# TODO: replace path with git/registry dep for publishing
    |mgroup3-native = { path = "$mgroup3NativePath" }
    |
    |[build-dependencies]
    |prost-build = "0.14"
    |""".trimMargin()

  private fun buildRs(): String = """
    |use std::io::Result;
    |
    |fn main() -> Result<()> {
    |    prost_build::compile_protos(&["proto/ast.proto"], &["proto"])?;
    |    Ok(())
    |}
    |""".trimMargin()

  private fun libRs(schema: AstSchema): String {
    val sb = StringBuilder()
    sb.append("// Generated by GenCli — do not edit by hand.\n\n")
    sb.append("pub mod proto {\n")
    sb.append("    include!(concat!(env!(\"OUT_DIR\"), \"/")
      .append(schema.packageName).append(".rs\"));\n")
    sb.append("}\n\n")

    for (e in schema.enums) {
      sb.append("#[derive(Debug, Clone, PartialEq, Eq)]\n")
      sb.append("pub enum ").append(e.name).append(" {\n")
      for (v in e.values) {
        sb.append("    ").append(rustEnumVariant(v)).append(",\n")
      }
      sb.append("}\n\n")
    }

    for (m in schema.messages) {
      if (m.sealedChildren.isNotEmpty()) {
        sb.append("#[derive(Debug, Clone)]\n")
        sb.append("pub enum ").append(m.name).append(" {\n")
        for (child in m.sealedChildren) {
          // Box 처리: enum variant 가 가리키는 자식 message 도 같은 cycle 일 수 있어서 항상 Box.
          sb.append("    ").append(child).append("(Box<").append(child).append(">),\n")
        }
        sb.append("}\n\n")
      } else {
        sb.append("#[derive(Debug, Clone)]\n")
        sb.append("pub struct ").append(m.name).append(" {\n")
        for (f in m.fields) {
          sb.append("    pub ").append(rustFieldName(f.name)).append(": ")
            .append(rustType(f.type)).append(",\n")
        }
        sb.append("}\n\n")
      }
    }

    sb.append(
      """
      |use mgroup3_native::proto::com::giyeok::jparser::mgroup3::proto::KernelsHistoryMsg;
      |
      |// TODO: Stage 4 — kernel history -> AST 변환 구현.
      |// KotlinOptCodeGen 의 매칭 로직을 Rust 로 포팅해야 함.
      |pub fn build_ast(_history: &KernelsHistoryMsg) -> () {
      |    unimplemented!("Stage 4 stub — kernel -> AST builder")
      |}
      |""".trimMargin()
    )
    return sb.toString()
  }

  private fun rustType(t: SchemaType): String = when (t) {
    SchemaType.Bool -> "bool"
    SchemaType.Int32 -> "i32"
    SchemaType.Str -> "String"
    SchemaType.NodeBytes -> "Vec<u8>"
    // Msg 참조는 self-referential cycle 을 피하기 위해 항상 Box. (정확한 SCC 분석은 추후 PR)
    is SchemaType.Msg -> "Box<" + t.name + ">"
    is SchemaType.Enm -> t.name
    is SchemaType.Opt -> "Option<" + rustType(t.of) + ">"
    is SchemaType.Arr -> "Vec<" + rustTypeUnboxed(t.of) + ">"  // Vec 자체가 heap 이라 inner Box 불필요
  }

  // Vec<_> inside: skip the outer Box on Msg since Vec is already heap-allocated.
  private fun rustTypeUnboxed(t: SchemaType): String = when (t) {
    is SchemaType.Msg -> t.name
    else -> rustType(t)
  }

  private fun rustFieldName(name: String): String {
    // Rust convention: snake_case. Reserved-word avoidance with trailing underscore.
    val sb = StringBuilder()
    for ((i, c) in name.withIndex()) {
      if (c.isUpperCase() && i > 0) sb.append('_')
      sb.append(c.lowercaseChar())
    }
    val out = sb.toString()
    return if (out in RUST_KEYWORDS) "${out}_" else out
  }

  private fun rustEnumVariant(name: String): String =
    if (name.isEmpty()) name else name[0].uppercaseChar() + name.substring(1)

  private val RUST_KEYWORDS = setOf(
    "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn",
    "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref",
    "return", "self", "Self", "static", "struct", "super", "trait", "true", "type", "unsafe",
    "use", "where", "while", "async", "await", "dyn", "abstract", "become", "box", "do",
    "final", "macro", "override", "priv", "typeof", "unsized", "virtual", "yield", "try",
  )
}
