package com.giyeok.jparser.mgroup3

import org.junit.jupiter.api.Test
import java.io.File
import java.nio.file.Path

/**
 * Generates a fixture file consumed by the Rust port at
 * `mgroup3-native/tests/accept_condition_diff.rs`.
 *
 * Each block represents one operation:
 *   - `display`  → check Display format (toString)
 *   - `neg`      → check `.neg()`
 *   - `and_from` → check `And.from(inputs)`
 *   - `or_from`  → check `Or.from(inputs)`
 *   - `evaluate` → check `evaluateAcceptCondition`
 *   - `evolve`   → check `evolveAcceptCondition`
 *
 * Block format (line-oriented, blank-line separated). Values are the literal
 * Kotlin `toString()` output. Multi-element lists use `|` as separator.
 *
 * Run once when the corpus changes. The output is committed to the Rust crate
 * so cargo test works offline.
 */
class AcceptConditionFixtureGenTest {
  @Test
  fun generate() {
    val out = StringBuilder()
    out.appendLine("# mgroup3 AcceptCondition fixture")
    out.appendLine("# Auto-generated by AcceptConditionFixtureGenTest. Do not edit.")
    out.appendLine("")

    emitDisplay(out)
    emitNeg(out)
    emitAndFrom(out)
    emitOrFrom(out)
    emitEvaluate(out)
    emitEvolve(out)

    val outPath = resolveOutputPath()
    outPath.parent.toFile().mkdirs()
    outPath.toFile().writeText(out.toString())
    println("wrote ${out.length} bytes to $outPath")
  }

  private fun resolveOutputPath(): Path {
    // Walk up from cwd looking for the `mgroup3-native` directory (sibling of mgroup3/).
    var dir: File? = File(System.getProperty("user.dir")).absoluteFile
    while (dir != null) {
      val candidate = File(dir, "mgroup3-native")
      if (candidate.isDirectory) {
        return File(candidate, "tests/fixtures/accept_condition.txt").toPath()
      }
      dir = dir.parentFile
    }
    error("could not locate mgroup3-native/ directory from cwd=${System.getProperty("user.dir")}")
  }

  // ----- emitters -----

  private fun emitBlock(out: StringBuilder, kind: String, fields: List<Pair<String, String>>) {
    out.appendLine("kind=$kind")
    for ((k, v) in fields) out.appendLine("$k=$v")
    out.appendLine("")
  }

  private fun emitDisplay(out: StringBuilder) {
    val cases = listOf<AcceptCondition>(
      Always,
      Never,
      NoLongerMatch(1, 2, false),
      NoLongerMatch(1, 2, true),
      NoLongerMatch(0, 0, false),
      NoLongerMatch(-1, Int.MAX_VALUE, false),
      NeedLongerMatch(1, 2, false),
      NeedLongerMatch(1, 2, true),
      NeedLongerMatch(0, 0, false),
      NotExists(3, 5),
      NotExists(0, 0),
      Exists(3, 5),
      Exists(0, 0),
      Unless(3, 5),
      Unless(0, 0),
      OnlyIf(3, 5),
      OnlyIf(0, 0),
      // Composites of size 2, 3, 4, 5
      And.from(listOf(Exists(1, 0), NotExists(2, 0))),
      And.from(listOf(Exists(1, 0), NotExists(2, 0), Exists(3, 0))),
      And.from(listOf(Exists(1, 0), NotExists(2, 0), Exists(3, 0), NotExists(4, 0))),
      And.from(listOf(Exists(1, 0), Exists(2, 0), Exists(3, 0), Exists(4, 0), Exists(5, 0))),
      Or.from(listOf(Exists(1, 0), NotExists(2, 0))),
      Or.from(listOf(Exists(1, 0), NotExists(2, 0), Exists(3, 0), NotExists(4, 0), Exists(5, 0))),
    )
    for (c in cases) {
      emitBlock(
        out, "display",
        listOf("cond" to c.toString(), "expected" to c.toString())
      )
    }
  }

  private fun emitNeg(out: StringBuilder) {
    val cases = listOf<AcceptCondition>(
      Always, Never,
      NoLongerMatch(1, 2, false),
      NoLongerMatch(1, 2, true),
      NeedLongerMatch(0, 0, false),
      Exists(3, 5),
      NotExists(3, 5),
      Unless(3, 5),
      OnlyIf(3, 5),
      And.from(listOf(Exists(1, 0), NotExists(2, 0))),
      Or.from(listOf(Exists(1, 0), And.from(listOf(NotExists(2, 0), Exists(3, 0))))),
    )
    for (c in cases) {
      emitBlock(
        out, "neg",
        listOf("cond" to c.toString(), "expected" to c.neg().toString())
      )
    }
  }

  private fun emitAndFrom(out: StringBuilder) {
    fun emit(inputs: List<AcceptCondition>) {
      val expected = And.from(inputs)
      emitBlock(
        out, "and_from",
        listOf(
          "inputs" to inputs.joinToString("|"),
          "expected" to expected.toString(),
        )
      )
    }
    // empty / single / all-identity / absorber / dedup / nested-flatten / size-5 / dedup-to-1
    emit(emptyList())
    emit(listOf(Exists(1, 0)))
    emit(listOf<AcceptCondition>(Always, Always, Always))
    emit(listOf<AcceptCondition>(Exists(1, 0), Never, Exists(2, 0)))
    emit(listOf(Exists(1, 0), Exists(1, 0), Exists(2, 0)))
    emit(listOf<AcceptCondition>(
      And.from(listOf(Exists(1, 0), Exists(2, 0))),
      Exists(3, 0),
    ))
    emit((0 until 5).map { Exists(it, 0) })
    emit(listOf(Exists(1, 0), Exists(1, 0), Exists(1, 0)))
  }

  private fun emitOrFrom(out: StringBuilder) {
    fun emit(inputs: List<AcceptCondition>) {
      val expected = Or.from(inputs)
      emitBlock(
        out, "or_from",
        listOf(
          "inputs" to inputs.joinToString("|"),
          "expected" to expected.toString(),
        )
      )
    }
    emit(emptyList())
    emit(listOf(Exists(1, 0)))
    emit(listOf<AcceptCondition>(Never, Never, Never))
    emit(listOf<AcceptCondition>(Exists(1, 0), Always, Exists(2, 0)))
    emit(listOf(Exists(1, 0), Exists(1, 0), Exists(2, 0)))
    emit(listOf<AcceptCondition>(
      Or.from(listOf(Exists(1, 0), Exists(2, 0))),
      Exists(3, 0),
    ))
    emit((0 until 5).map { Exists(it, 0) })
  }

  private fun emitEvaluate(out: StringBuilder) {
    data class EvCase(
      val cond: AcceptCondition,
      val fins: Map<PathRoot, AcceptCondition>,
      val active: Set<PathRoot>,
      val expected: Boolean,
    )
    val cases = listOf(
      EvCase(Always, emptyMap(), emptySet(), true),
      EvCase(Never, emptyMap(), emptySet(), false),
      // NoLongerMatch: no fin → true; fin=Always → false
      EvCase(NoLongerMatch(1, 2, false), emptyMap(), emptySet(), true),
      EvCase(NoLongerMatch(1, 2, false), mapOf(PathRoot(1, 2) to Always), emptySet(), false),
      // NeedLongerMatch: no fin → false; fin=Always → true
      EvCase(NeedLongerMatch(1, 2, false), emptyMap(), emptySet(), false),
      EvCase(NeedLongerMatch(1, 2, false), mapOf(PathRoot(1, 2) to Always), emptySet(), true),
      // Exists/NotExists/Unless/OnlyIf
      EvCase(Exists(1, 2), mapOf(PathRoot(1, 2) to Always), emptySet(), true),
      EvCase(Exists(9, 9), emptyMap(), emptySet(), false),
      EvCase(NotExists(1, 2), mapOf(PathRoot(1, 2) to Always), emptySet(), false),
      EvCase(NotExists(9, 9), emptyMap(), emptySet(), true),
      EvCase(Unless(1, 2), mapOf(PathRoot(1, 2) to Always), emptySet(), false),
      EvCase(Unless(9, 9), emptyMap(), emptySet(), true),
      EvCase(OnlyIf(1, 2), mapOf(PathRoot(1, 2) to Always), emptySet(), true),
      EvCase(OnlyIf(9, 9), emptyMap(), emptySet(), false),
      // composites
      EvCase(
        And.from(listOf(Exists(1, 0), Exists(2, 0))),
        mapOf(PathRoot(1, 0) to Always, PathRoot(2, 0) to Always),
        emptySet(),
        true,
      ),
      EvCase(
        And.from(listOf(Exists(1, 0), Exists(2, 0))),
        mapOf(PathRoot(1, 0) to Always),
        emptySet(),
        false,
      ),
      EvCase(
        Or.from(listOf(Exists(1, 0), Exists(2, 0))),
        mapOf(PathRoot(1, 0) to Always),
        emptySet(),
        true,
      ),
    )
    for (c in cases) {
      emitBlock(
        out, "evaluate",
        listOf(
          "cond" to c.cond.toString(),
          "finsKeys" to c.fins.keys.joinToString("|"),
          "finsValues" to c.fins.values.joinToString("|"),
          "active" to c.active.joinToString("|"),
          "expected" to c.expected.toString(),
        )
      )
    }
  }

  private fun emitEvolve(out: StringBuilder) {
    data class EvolveCase(
      val cond: AcceptCondition,
      val fins: Map<PathRoot, AcceptCondition>,
      val active: Set<PathRoot>,
      val gen: Int,
    )
    val cases = mutableListOf<EvolveCase>()

    // 6 leaves x {no fin/no active, fin no cycle, fin with cycle, active only}
    val leafFactories: List<(Int, Int) -> AcceptCondition> = listOf(
      { s, g -> NoLongerMatch(s, g, false) },
      { s, g -> NeedLongerMatch(s, g, false) },
      { s, g -> NotExists(s, g) },
      { s, g -> Exists(s, g) },
      { s, g -> Unless(s, g) },
      { s, g -> OnlyIf(s, g) },
    )
    for (mk in leafFactories) {
      val leaf = mk(1, 0)
      val root = PathRoot(1, 0)
      // 1) no fin, no active
      cases.add(EvolveCase(leaf, emptyMap(), emptySet(), 10))
      // 2) fin no cycle (fin = Always; root not referenced again)
      cases.add(EvolveCase(leaf, mapOf(root to Always), emptySet(), 10))
      // 3) fin with cycle (fin references same root through the same leaf type)
      cases.add(EvolveCase(leaf, mapOf(root to mk(1, 0)), emptySet(), 10))
      // 4) active only
      cases.add(EvolveCase(leaf, emptyMap(), setOf(root), 10))
    }
    // fromNextGen=true strips flag
    cases.add(EvolveCase(NoLongerMatch(1, 2, true), emptyMap(), emptySet(), 10))
    cases.add(EvolveCase(NeedLongerMatch(1, 2, true), emptyMap(), emptySet(), 10))
    // composite
    cases.add(EvolveCase(
      And.from(listOf(NoLongerMatch(2, 4, false), Exists(5, 1))),
      mapOf(PathRoot(2, 4) to NotExists(2, 4), PathRoot(5, 1) to Always),
      setOf(PathRoot(5, 1)),
      10,
    ))
    cases.add(EvolveCase(
      Or.from(listOf(NoLongerMatch(2, 4, false), Exists(5, 1))),
      mapOf(PathRoot(2, 4) to NotExists(2, 4)),
      emptySet(),
      10,
    ))

    for (c in cases) {
      val expected = evolveAcceptCondition(c.cond, c.fins, c.active, c.gen)
      emitBlock(
        out, "evolve",
        listOf(
          "cond" to c.cond.toString(),
          "finsKeys" to c.fins.keys.joinToString("|"),
          "finsValues" to c.fins.values.joinToString("|"),
          "active" to c.active.joinToString("|"),
          "gen" to c.gen.toString(),
          "expected" to expected.toString(),
        )
      )
    }
  }
}
